config/routes.rb
Rails.application.routes.draw do
    # Login/OAuth routes
    get "/login", to: redirect("/auth/google_oauth2")
    get "/auth/google_oauth2/callback", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/logout", to: "sessions#destroy"

    # Student Roster routes
    get    '/users/:user_id/courses/:id/student_index', to: 'courses#student_index'

    # Flashcard routes
    get    '/users/:user_id/courses/:id/flashcard',  to: 'courses#flashcard'
    get    '/users/:user_id/courses/:id/quiz',  to: 'courses#quiz'
    post   '/users/:user_id/courses/:id/update_notes',  to: 'courses#updateNotes'
    post   '/users/:user_id/courses/:id', to: 'courses#edit_flashcard_order'


    # Poll routes
    get    '/p/:access_tag', to: 'polls#student_show'
    get    '/p/:access_tag/o/:option_id/select', to: 'options#select'
    get    'user/:user_id/course/:course_id/poll/:id/data', to: 'polls#get_data'


    # Assignment routes
    get    '/a/:access_tag/search',  to: 'submissions#search'
    get    '/a/:access_tag', to: 'submissions#new'
    post   '/a/:access_tag', to: 'submissions#create'
    post   '/users/:user_id/courses/:id/assignments/:assignment_id/submissions/:id/edit', to: 'submissions#update'
    get    '/users/:user_id/courses/:course_id/assignments/:id/submissions', to: 'assignments#get_submission_data'

    # frontpage/submission routes
    get 'homepage/index'
    get    '/:access_tag', to: 'homepage#access_submission_page'

    resources :users do
        resources :courses do
            resources :students do
                collection do
                    post :import
                end
            end
            resources :polls do
                resources :options
            end
            resources :assignments do
                resources :submissions
            end
        end
    end

    resource :session, only: [:create, :destroy]

    root 'homepage#index'
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :course
    has_attached_file :portrait, styles: { flashcard: "300x300#", small: "100x100#" }, :default_url => "/images/defaults/:style/missing.png"
    validates_attachment_content_type :portrait, content_type: /\Aimage\/.*\z/
    validates :name,
            length: {maximum: 50 }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @students = @course.students
    end

    def new
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @student = @course.students.new
    end

    def create
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @student = @course.students.create(student_params)
        if @student.save
            redirect_to user_course_student_path(@user, @course, @student)
        else
            render 'new'
      end
    end

    def show
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @student = @course.students.find(params[:id])
    end

    def destroy
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @student = @course.students.find(params[:id])
        @student.destroy
        redirect_to controller: 'courses', action: 'student_index', user_id: @user, id: @course
    end

    def edit
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @student = @course.students.find(params[:id])
    end

    def update
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @student = @course.students.find(params[:id])

        if @student.update(student_params)
            redirect_to controller: 'courses', action: 'student_index', user_id: @user, id: @course
        else
            render 'edit'
        end
    end

    # Handles student upload from an image file. Called on a per file basis.
    # The name of the file (minus the file extension) will be the name of the student.
    def import
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        # Create a new student to be populated
        student = Student.new
        student.course_id = @course.id
        student.portrait = params[:file]
        # The name of the student is the name of the image
        student.name = student.portrait_file_name
        # Check that an image was actually grabbed by ensuring name is not empty or nil
        if student.name != "" and student.name != nil
            # Replace all underscores with spaces, as file names convert spaces to underscores
            if student.name.include? "_"
                student.name.gsub!("_", " ")
            end
            # Get rid of the file extension
            name_array = student.name.split(".")[0..-2]
            student.name = name_array.join(".")
            student.save
        end

        redirect_to controller: 'courses', action: 'student_index', user_id: @user, id: @course
    end

    private
        def student_params
            params.require(:student).permit(:name, :email, :portrait, :notes,
                                            :in_flashcards, :in_quiz)
        end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<center>
<%= form_for [@user, @course, @student], local: true, html: {:class => "form-horizontal"} do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr class="field">
      <td><%= form.label :name,  :class => "control-label"  %></td>
      <td><%= form.text_field :name,  :class => "name" %></td>
    </tr>

    <tr class="field">
      <td><%= form.label :email,  :class => "control-label"  %></td>
      <td><%= form.text_field :email, :class => "email" %></td>
    </tr>

    <tr class="field">
      <td><%= form.label :notes,  :class => "control-label"  %></td>
      <td><%= form.text_field :notes, :class => "notes" %></td>
    </tr>

    <tr class="field">
      <td><%= form.label :portrait,  :class => "control-label"  %></td>
      <td><%= form.file_field :portrait, :class => "portrait" %></td>
    </tr>

    <tr class="field">
      <td align="right"><%= form.check_box :in_flashcards, :checked => @student.in_flashcards %> </td>
      <td><%= form.label :in_flashcards, "Include in flashcards", :class => "control-label"  %> </td>
    </tr>

    <tr class="field">
      <td align="right"><%= form.check_box :in_quiz, :checked => @student.in_quiz %> </td>
      <td><%= form.label :in_quiz, "Include in quiz", :class => "control-label"  %> </td>
    </tr>

  </table>
  <br>
  <%= form.submit "Confirm", :class => "btn"  %>
  <%= link_to cancel_text, cancel_path, :class => "btn btn-danger" %>
<% end %>
</center>
<br>
<center>
<h3>Batch Upload</h3>
<div class="drop-area">
  <%= form_tag import_user_course_students_path(@user, @course), :class => "dropzone", multipart: true do %>
</div>
  <%= submit_tag "Import" %>
<% end %>
</center>

app/views/students/edit.html.erb
<center>
  <br>
  <div>
    <h1>Edit Student</h1>
    <hr>
    <%= render partial: 'form', locals: {cancel_path: user_course_path(@user, @course), cancel_text: "Cancel"} %>
  </div>
</center>

app/views/students/index.html.erb
<%= render 'courses/header', course: "", edit: "", students: "active", quiz: "", assignments: "" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-6"><h1>Student Roster</h1></div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6" >
      <h1 class="right-align"><%= link_to "Add Student", new_user_course_student_path(@user, @course), :class => 'btn'%></h1>
    </div>
  </div>

<body>
<table class="table table-hover table-responsive">
  <tr class="medium-purple">
    <th class="col-lg-3 col-md-3 col-sm-4">Name</th>
    <th class="col-lg-6 col-md-6 col-sm-4">Notes</th>
    <th class="col-lg-3 col-md-3 col-sm-4" > <center>Options</center></th>
  </tr>

  <% @students.each do |student| %>
    <tr >
      <td class="col-lg-3 col-md-3 col-sm-4">
        <%= image_tag student.portrait.url(:small)%>
        <%= link_to "student.name", user_course_student_path(@user, @course, student) %>
      </td>
      <td class="col-lg-6 col-md-6 col-sm-4"><%= student.notes %></td>
      <td class="col-lg-3 col-md-3 col-sm-4" align="center">
        <div class="row">
          <a class="col-4"><%= link_to edit_user_course_student_path(@user, @course, student) do %>
            <span class="glyphicon glyphicon-edit" ></span>
          <% end %></a>
          <a class="col-4"><%= link_to user_course_student_path(@user, @course, student),
              method: :delete,
              data: { confirm: 'Are you sure?' } do %>
                 <span class="glyphicon glyphicon-trash" ></span>
                <% end %></a>
          <br>
          <%= form_for [@user, @course, student], local: true, html: {:class => "form-horizontal"} do |form| %>
          <table>
            <td class="col-6">
                <%= form.check_box :in_flashcards, :checked => student.in_flashcards %>
                <%= form.label :in_flashcards, "Include in flashcards", :class => "control-label"  %>
                <br>
                <%= form.check_box :in_quiz, :checked => student.in_quiz %>
                <%= form.label :in_quiz, "Include in quiz", :class => "control-label"  %>
            </td>
            <td class="col-6">
              <%= form.submit "Confirm", :class => "btn"  %>
            <% end %>
            </td>
          </table>
        </div>
      </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>
</div>

<center>
    <h4>Import Students</h4>
    <div class = "drop-area">
      <%= form_tag import_user_course_students_path(@user, @course),
        :class => "dropzone",
        multipart: true do %>
    </div>
      <%= submit_tag "Import" %>
      <% end %>
    <br>
    <br>
</center>

</body>

app/views/students/index.js.erb
$(".index").html("<%= escape_javascript(render('index')) %>")

app/views/students/new.html.erb
<center>
    <br>
    <div>
        <h1>New Student</h1>
        <hr>
        <%= render partial: 'form', locals: {cancel_path: user_courses_path(@user, @course), cancel_text: "Cancel"} %>
    </div>
</center>

app/views/students/show.html.erb
<center>
  <br>
    <div>
      <ul class="nav nav-pills nav-justified">
      <li class = "active"><a href="#">Show Student</a><br></li>
      <li ><%= link_to "Edit Student", edit_user_course_student_path(@user, @course, @student) %><br></li>
      <li><%= link_to "Back to Course", user_course_path(@user, @course)%><br></li>
      </ul>

      <h2><%= @student.name %></h2>
      <h4><%= @student.email %></h4>
      <%= image_tag @student.portrait.url(:flashcard)%>
      <h4>Notes</h4>
      <p> <%= @student.notes %> </p>
      <hr>
    </div>
</center>