config/routes.rb
Rails.application.routes.draw do
    # Login/OAuth routes
    get "/login", to: redirect("/auth/google_oauth2")
    get "/auth/google_oauth2/callback", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/logout", to: "sessions#destroy"

    # Student Roster routes
    get    '/users/:user_id/courses/:id/student_index', to: 'courses#student_index'

    # Flashcard routes
    get    '/users/:user_id/courses/:id/flashcard',  to: 'courses#flashcard'
    get    '/users/:user_id/courses/:id/quiz',  to: 'courses#quiz'
    post   '/users/:user_id/courses/:id/update_notes',  to: 'courses#updateNotes'
    post   '/users/:user_id/courses/:id', to: 'courses#edit_flashcard_order'


    # Poll routes
    get    '/p/:access_tag', to: 'polls#student_show'
    get    '/p/:access_tag/o/:option_id/select', to: 'options#select'
    get    'user/:user_id/course/:course_id/poll/:id/data', to: 'polls#get_data'


    # Assignment routes
    get    '/a/:access_tag/search',  to: 'submissions#search'
    get    '/a/:access_tag', to: 'submissions#new'
    post   '/a/:access_tag', to: 'submissions#create'
    post   '/users/:user_id/courses/:id/assignments/:assignment_id/submissions/:id/edit', to: 'submissions#update'
    get    '/users/:user_id/courses/:course_id/assignments/:id/submissions', to: 'assignments#get_submission_data'

    # frontpage/submission routes
    get 'homepage/index'
    get    '/:access_tag', to: 'homepage#access_submission_page'

    resources :users do
        resources :courses do
            resources :students do
                collection do
                    post :import
                end
            end
            resources :polls do
                resources :options
            end
            resources :assignments do
                resources :submissions
            end
        end
    end

    resource :session, only: [:create, :destroy]

    root 'homepage#index'
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :poll
    validates :description,
                length: {maximum: 50 }
    validates :label, presence: true,
     			length: {maximum: 5 }
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
    include Hasher
    def new
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:poll_id])
        @option = @poll.options.new
    end

    def show
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:poll_id])
        @option = @poll.options.find(params[:id])
    end

    def create
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:poll_id])
        @option = @poll.options.create(option_params)
        if @option.save
            redirect_to user_course_poll_path(@user, @course, @poll)
        else
            render 'new'
        end
    end

    def destroy
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:poll_id])
        @option = @poll.options.find(params[:id])
        @option.destroy

        redirect_to user_course_poll_path(@user, @course, @poll)
    end

    def edit
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:poll_id])
        @option = @poll.options.find(params[:id])
    end

    def update
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:poll_id])
        @option = @poll.options.find(params[:id])
        if @option.update(option_params)
            redirect_to user_course_poll_path(@user, @course, @poll)
        else
            render 'edit'
        end
    end

    # Called when a student chooses the specific option from their screen
    def select
        @poll = Poll.find(unhashTagtoID(params[:access_tag]))
        @option = @poll.options.find(params[:option_id])
        @option.votes = @option.votes + 1
        @option.save

        render 'options/select'
    end

    private
        def option_params
            params.require(:option).permit(:label, :description, :votes)
        end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_for [@user, @course, @poll, @option], local: true, html: {:class => "form-horizontal"} do |form| %>
  <% if @option.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@option.errors.count, "error") %> prohibited
        this option from being saved:
      </h2>
      <ul>
        <% @option.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr class="field">
      <td><%= form.label :label,  :class => "control-label"  %></td>
      <td><%= form.text_field :label,  :class => "name" %></td>
    </tr>

    <tr class="field">
      <td><%= form.label :description,  :class => "control-label"  %></td>
      <td><%= form.text_area :description, :class => "description" %></td>
    </tr>
  </table>
  <%= form.submit "Confirm", :class => "btn btn-primary"  %>
  <%= link_to cancel_text, cancel_path, :class => "btn btn-danger"  %>
<% end %>

app/views/options/edit.html.erb
<center>
  <br>
  <div>
    <h1>Edit Option</h1>
    <hr>
    <%= render partial: 'form', locals: {cancel_path: user_course_poll_path(@user, @course, @poll), cancel_text: "Cancel"} %>
  </div>
</center>

app/views/options/new.html.erb
<center>
    <br>
    <div>
        <h1>New Option</h1>
        <hr>
        <%= render partial: 'form', locals: {cancel_path: user_course_poll_path(@user, @course, @poll), cancel_text: "Cancel"} %>
    </div>
</center>

app/views/options/select.html.erb
<center>
    <h2>Thanks for answering!</h2>
    <br>
    <%= link_to 'Submit another Response', :back , class: "btn btn-lg"%>
</center>

app/views/options/show.html.erb
<center>
  <br>
    <div>
      <%= link_to "Edit Option", edit_user_course_poll_option_path(@user, @course, @poll, @option) %>
      <%= link_to "Back to Poll", user_course_poll_path(@user, @course, @poll) %>
      <%= link_to "Back to Course", user_course_path(@user, @course) %>
      <%= link_to "Account", user_path(@user) %>
      <%= link_to 'Obliterate', user_course_poll_option_path(@user, @course, @poll, @option),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      <h2><%= @option.label %> : <%= @option.votes %> </h2>
      <p><%= @poll.description %></p>
      <hr>
      <br><br><br>
    </div>