config/routes.rb
Rails.application.routes.draw do
    # Login/OAuth routes
    get "/login", to: redirect("/auth/google_oauth2")
    get "/auth/google_oauth2/callback", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/logout", to: "sessions#destroy"

    # Student Roster routes
    get    '/users/:user_id/courses/:id/student_index', to: 'courses#student_index'

    # Flashcard routes
    get    '/users/:user_id/courses/:id/flashcard',  to: 'courses#flashcard'
    get    '/users/:user_id/courses/:id/quiz',  to: 'courses#quiz'
    post   '/users/:user_id/courses/:id/update_notes',  to: 'courses#updateNotes'
    post   '/users/:user_id/courses/:id', to: 'courses#edit_flashcard_order'


    # Poll routes
    get    '/p/:access_tag', to: 'polls#student_show'
    get    '/p/:access_tag/o/:option_id/select', to: 'options#select'
    get    'user/:user_id/course/:course_id/poll/:id/data', to: 'polls#get_data'


    # Assignment routes
    get    '/a/:access_tag/search',  to: 'submissions#search'
    get    '/a/:access_tag', to: 'submissions#new'
    post   '/a/:access_tag', to: 'submissions#create'
    post   '/users/:user_id/courses/:id/assignments/:assignment_id/submissions/:id/edit', to: 'submissions#update'
    get    '/users/:user_id/courses/:course_id/assignments/:id/submissions', to: 'assignments#get_submission_data'

    # frontpage/submission routes
    get 'homepage/index'
    get    '/:access_tag', to: 'homepage#access_submission_page'

    resources :users do
        resources :courses do
            resources :students do
                collection do
                    post :import
                end
            end
            resources :polls do
                resources :options
            end
            resources :assignments do
                resources :submissions
            end
        end
    end

    resource :session, only: [:create, :destroy]

    root 'homepage#index'
end

app/models/poll.rb
class Poll < ApplicationRecord
    belongs_to :course
    has_many :options, :dependent => :destroy
    validates :name, presence: true,
                     length: { minimum: 3, maximum: 20 }
    validates :description,
                length: {maximum: 100 }
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
    include Hasher

    def index
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @polls = @course.polls
    end

    def new
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.new
    end

    def create
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.create(poll_params)
        if @poll.save
            redirect_to user_course_poll_path(@user, @course, @poll)
        else
            render 'new'
      end
    end

    # For the user (professor)
    def show
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:id])
        @pollTag = hashIDtoTag(@poll.id, true) # this is a poll
        @options = @poll.options
    end

    # for getting the json data
    def get_data
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:id])
        @options = @poll.options
        @data = Hash.new(0)
        @options.each do |option|
            tag = option.label + ": " + option.description
            @data[tag] = option.votes
        end
        render(json: @data)
    end

    # For the students on their phones
    def student_show
        @access_tag = params[:access_tag]
        id = unhashTagtoID(@access_tag)
        if Poll.exists?(id)
            @poll = Poll.find(id)
            @options = @poll.options
        else
            render "homepage/invalid_tag"
        end
    end

    def destroy
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:id])
        @poll.destroy

        redirect_to user_course_path(@user, @course)
    end

    def edit
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:id])
    end

    def update
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:course_id])
        @poll = @course.polls.find(params[:id])

        if @poll.update(poll_params)
            redirect_to user_course_poll_path(@user, @course, @poll)
        else
            render 'edit'
        end
    end

    private
        def poll_params
            params.require(:poll).permit(:name, :description)
        end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for [@user, @course, @poll], local: true, html: {:class => "form-horizontal"} do |form| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@poll.errors.count, "error") %> prohibited
        this poll from being saved:
      </h2>
      <ul>
        <% @poll.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr class="field">
      <td><%= form.label :name,  :class => "control-label"  %></td>
      <td><%= form.text_field :name,  :class => "name" %></td>
    </tr>

    <tr class="field">
      <td><%= form.label :description,  :class => "control-label"  %></td>
      <td><%= form.text_area :description, :class => "description" %></td>
    </tr>
  </table>
  <%= form.submit "Confirm" , :class => "btn btn-primary" %>
  <%= link_to cancel_text, cancel_path , :class => "btn btn-danger" %>
<% end %>

app/views/polls/edit.html.erb
<center>
  <br>
  <div>
    <h1>Edit Poll</h1>
    <hr>
    <%= render partial: 'form', locals: {cancel_path: user_course_path(@user, @course), cancel_text: "Cancel"} %>
  </div>
</center>

app/views/polls/index.html.erb
<%= render 'courses/header', course: "", edit: "", students: "", quiz: "", assignments: "", polls: "active" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-6"><h1>Polls</h1></div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6" >
      <h1 class="right-align"><%= link_to "New Poll", new_user_course_poll_path(@user, @course), :class => "btn" %></h1>
    </div>
  </div>
    <center>
      <table class="table table-hover table-responsive">
        <tr class="table-header">
          <th class="col-lg-3 col-md-3 col-sm-3">Name</th>
          <th class="col-lg-5 col-md-5 col-sm-5">Description</th>
          <th class="col-lg-2 col-md-2 col-sm-2" >Date Created</th>
          <th class="col-lg-2 col-md-2 col-sm-2" > <center>Options</center></th>
        </tr>
        <% @polls.each do |poll| %>
          <tr data-link="<%= user_course_poll_path(@user, @course, poll) %>">
            <td class="col-lg-3"><%= poll.name %></td>
            <td class="col-lg-5"><%= poll.description %></td>
            <td class="col-lg-2"><%= poll.created_at.strftime("%A, %B %-d, %Y") %></td>
            <td class="col-lg-2" align="center">
                  <a ><%= link_to 'Show', user_course_poll_path(@user, @course, poll) %></a>
                  <a ><%= link_to 'Edit', edit_user_course_poll_path(@user, @course, poll) %></a>
                  <a ><%= link_to 'Destroy', user_course_poll_path(@user, @course, poll),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %> </a>
            </td>
          </tr>
        <% end %>
        <script> $("tr[data-link]").click(function() {
                window.location = $(this).data("link")
               })
        </script>
      </center>
    </body>
</center>

app/views/polls/new.html.erb
<center>
    <br>
    <div>
        <h1>New Poll</h1>
        <hr>
        <%= render partial: 'form', locals: {cancel_path: user_course_path(@user, @course), cancel_text: "Cancel"} %>
    </div>
</center>

app/views/polls/show.html.erb
<%= link_to "Back to Course", user_course_path(@user, @course), :class =>"btn btn-lg btn-primary" %>
<center>
<h1><%= @poll.name %>
  <a class="col-4"><%= link_to edit_user_course_poll_path(@user, @course, @poll) do %>
    <span class="glyphicon glyphicon-edit" ></span>
    <% end %></a></h1>
<h4>ACCESS TAG: <%= @pollTag %></h4>
<p><%= @poll.description %></p>

<div class="container">
  <table class="table table-hover table-responsive">
    <tr class="table-header">
      <td class="col-lg-3">Option</td>
      <td class="col-lg-5">Description</td>
      <td class="col-lg-2">Votes</td>
      <td class="col-lg-2">
        <center>
        <%= link_to "Add Option", new_user_course_poll_option_path(@user, @course, @poll), :class =>"btn btn-sm"%>
      </center>
      </td>
    </tr>
    <% @options.each do |option| %>
      <tr data-link="<%= user_course_poll_option_path(@user, @course, @poll, option) %>">
        <td class="col-lg-3"><%= option.label %></td>
        <td class="col-lg-5"><%= option.description %></td>
        <td class="col-lg-2"><%= option.votes %></td>
        <td class="col-lg-2" align="center">
          <a class="col-6"><%= link_to edit_user_course_poll_option_path(@user, @course, @poll, option) do %>
            <span class="glyphicon glyphicon-edit" ></span>
            <% end %></a>
          <a class="col-6"><%= link_to  user_course_poll_option_path(@user, @course, @poll, option),
            method: :delete,
            data: { confirm: 'Are you sure?' } do %>
               <span class="glyphicon glyphicon-trash" ></span>
              <% end %></a>
        </td>
      </tr>
    <% end %>
    <script> $("tr[data-link]").click(function() {
                window.location = $(this).data("link")
               })
    </script>
  </table>
</div>

<br><br><br>
<br><br><br>
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <%= pie_chart url_for(controller:'polls', action:'get_data'), refresh: 5%>
    </div>
    <div class="col-lg-6">
    <%= bar_chart url_for(controller:'polls', action:'get_data'), refresh: 5%>
  </div>
  </div>
</div>
<br><br><br>
</div>

<%= link_to 'Destroy Poll', user_course_poll_path(@user, @course, @poll),
          method: :delete,
          data: { confirm: 'Are you sure?' }, :class =>"btn btn-danger"  %>
</center>
<br><br><br>

app/views/polls/student_show.html.erb
<center>
  <br>
    <div>
      <h2><%= @poll.name %></h2>
      <p><%= @poll.description %></p>
      <hr>
      <% @options.each do |option| %>
        <tr class= "row">
          <td class="col-lg-2" align="center">
                <%= link_to (option.label + ": " + truncate(option.description, length: 17, omission: '...')), url_for(controller: "options", action:"select", access_tag: @access_tag, option_id: option.id), class: "poll-option-button"%><br>
          </td>
        </tr>
      <% end %>
      <br><br><br>
    </div>