config/routes.rb
Rails.application.routes.draw do
    # Login/OAuth routes
    get "/login", to: redirect("/auth/google_oauth2")
    get "/auth/google_oauth2/callback", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/logout", to: "sessions#destroy"

    # Student Roster routes
    get    '/users/:user_id/courses/:id/student_index', to: 'courses#student_index'

    # Flashcard routes
    get    '/users/:user_id/courses/:id/flashcard',  to: 'courses#flashcard'
    get    '/users/:user_id/courses/:id/quiz',  to: 'courses#quiz'
    post   '/users/:user_id/courses/:id/update_notes',  to: 'courses#updateNotes'
    post   '/users/:user_id/courses/:id', to: 'courses#edit_flashcard_order'


    # Poll routes
    get    '/p/:access_tag', to: 'polls#student_show'
    get    '/p/:access_tag/o/:option_id/select', to: 'options#select'
    get    'user/:user_id/course/:course_id/poll/:id/data', to: 'polls#get_data'


    # Assignment routes
    get    '/a/:access_tag/search',  to: 'submissions#search'
    get    '/a/:access_tag', to: 'submissions#new'
    post   '/a/:access_tag', to: 'submissions#create'
    post   '/users/:user_id/courses/:id/assignments/:assignment_id/submissions/:id/edit', to: 'submissions#update'
    get    '/users/:user_id/courses/:course_id/assignments/:id/submissions', to: 'assignments#get_submission_data'

    # frontpage/submission routes
    get 'homepage/index'
    get    '/:access_tag', to: 'homepage#access_submission_page'

    resources :users do
        resources :courses do
            resources :students do
                collection do
                    post :import
                end
            end
            resources :polls do
                resources :options
            end
            resources :assignments do
                resources :submissions
            end
        end
    end

    resource :session, only: [:create, :destroy]

    root 'homepage#index'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        courses = @user.courses
        @ordered_courses = Array.new
        @ordered_courses = courses.sort_by {|course| [course.year, course.semester.downcase, course.code.downcase, course.section]}
        @ordered_courses = @ordered_courses.reverse
    end

    def student_index
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
        @students = @course.students
    end

    def show
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
    end

    def new
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.new
    end

    def create
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.create(course_params)

        if @course.save
            redirect_to user_course_path(@user, @course)
        else
            render 'new'
      end
    end

    def edit
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
    end

    def update
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])

        if @course.update(course_params)
            redirect_to user_course_path(@user, @course)
        else
            render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
        @course.destroy
        redirect_to user_courses_path(@user)
    end

    def quiz
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
    end

    def edit_flashcard_order
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
        @course.flashcard_order = params[:flashcard_order]["edit_flashcard_order"]
        @course.save

        redirect_to user_course_path(@user, @course)
    end

    def flashcard
        # get the user and course paramaters
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
        @type = params[:type]

        if @type == "equity"
            # Handles Equity Drawing of Flashcards

            # If the user has never ordered the flashcards, flashcard_order will be nil.
            if @course.flashcard_order != nil
                student_list = @course.flashcard_order.split("\n")
            else
                student_list = Array.new
            end

            # first see if there is a specified student to be selected
            # if there is, pick the first student from the list
            if student_list.length == 0
                # if the list to draw from is empty, just randomly select one student from the course roster
                @flashcard_student = @course.students.where(in_flashcards: true).sample
            else
                # Get the first name of the list, and remove any leading or trailing white space
                student_name = student_list[0].rstrip
                student_name = student_name.lstrip
                @flashcard_student = Student.find_by(name: student_name)
                # Remove this student from the ordering
                new_flashcard_order = student_list[1..-1].join("\n")
                @course.flashcard_order = new_flashcard_order
                @course.save
            end
            # if there is a student to show
            if @flashcard_student != nil
                # convert the student object to a hash
                @student_hash = @flashcard_student.attributes
                # add the student's portrait url to the hash
                @student_hash[:portrait_url] = @flashcard_student.portrait.url(:flashcard)
            else
                # otherwise send back an empty object
                @student_hash = {};
            end

        elsif @type == "quiz"

            # Handles Quiz Drawing of Flashcards

            @quiz_student = @course.students.where(in_quiz: true).sample
            # if there is a student to show
            if @quiz_student != nil
                # convert the student object to a hash
                @student_hash = @quiz_student.attributes
                # add the student's portrait url to the hash
                @student_hash[:portrait_url] = @quiz_student.portrait.url(:flashcard)
            else
                # otherwise send back an empty object
                @student_hash = {};
            end
        end
        # send the json back to the client
        render(json:  @student_hash)
    end

    def updateNotes
        @user = User.find(params[:user_id])
        ensure_proper_user(@user)
        @course = @user.courses.find(params[:id])
        @student = @course.students.find(params[:student_id])
        @student.notes = params[:notes]
        if @student.save
            render(json:  {status: "ok"})
        else
            render(json:  {status: "failure"})
        end
    end

    private
        def course_params
            params.require(:course).permit(:title, :code, :semester, :section, :year)
        end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for [@user, @course], local: true, html: {:class => "form-horizontal"} do |form| %>
  <% if @course.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr class="field">
      <td><%= form.label :title,  :class => "control-label"  %></td>
      <td><%= form.text_field :title,  :class => "title", :placeholder => "Intro to Computer Science"%></td>
    </tr>

    <tr class="field">
      <td><%= form.label :code,  :class => "control-label"  %></td>
      <td><%= form.text_field :code, :class => "code", :placeholder => "CS5" %></td>
    </tr>
    <tr class="field">
      <td><%= form.label :section,  :class => "control-label"  %></td>
      <td><%= form.number_field :section %></td>
    </tr>
    <tr class="field">
      <td><%= form.label :year,  :class => "control-label"  %></td>
      <td><%= form.number_field :year, :value => Date.today.year %></td>
    </tr>
    <tr class="field">
      <td><%= form.label :semester,  :class => "control-label"  %></td>
      <td><%= form.select :semester, ['FA', 'SP', 'SU'] %></td>
    </tr>
  </table>

  <%= form.submit "Confirm", :class => "btn" %>
  <%= link_to cancel_text, cancel_path, :class => "btn btn-danger" %>
<% end %>

app/views/courses/_header.html.erb
<center>
  <div class = "jumbotron">
    <h1 class="display-3"> <%= @course.code %>: <%= @course.title %></h1>
    
  </div>
  <ul class="nav nav-pills nav-justified">
    <li class = <%=course%>><%= link_to "Equity Cards", user_course_path(@user, @course) %><br></li>
    <li class = <%=students%>><%= link_to "Student Roster", {controller:"courses", action:"student_index", id:@course} %><br></li>
    <li class = <%=quiz%>><%= link_to "Face/Name Quiz", {controller:"courses", action:"quiz", id:@course} %><br></li>
    <li class = <%=assignments%>><%= link_to "Assignments", user_course_assignments_path(@user, @course) %><br></li>
    <li class = <%=polls%>><%= link_to "Polls", user_course_polls_path(@user, @course) %><br></li>
  </ul>
</center>

app/views/courses/_index.html.erb
<% @students.each do |student| %>
  <div class="img-thumbnail"><%= image_tag student.portrait.url(:thumb), alt: student.portrait.url(:thumb) %></div>
<% end %>

app/views/courses/edit.html.erb
<%= render 'header', course: "", students: "", quiz: "", assignments: "", polls: "" %>
<center>
    <br>
    <div>
        <h1>Edit Course</h1>
        <hr>
        <%= render partial: 'form', locals: {cancel_path: user_course_path(@user, @course), cancel_text: "Cancel"} %>
    </div>
</center>

app/views/courses/index.html.erb
<div class="container-fluid">
  <div class="row">
      <div class="col-lg-8 col-md-6 col-sm-4"><h1>Listing Courses</h1></div>
      <div class="col-lg-4 col-md-6 col-sm-8" style="text-align:right;"><h1><%= link_to "New Course", new_user_course_path(@user), :class => "btn"%></h1></div>
  </div>

<table class="table table-hover table-responsive">
  <thead >
    <tr class= "row"; style="background-color:rgb(78,55,100,.5);">
      <th class="col-lg-4">Title</th>
      <th class="col-lg-4">Code</th>
      <th class="col-lg-4"> <center>Options</center></th>
    </tr>
  </thead>

  <% @ordered_courses.each do |course| %>
    <tr data-link="<%= user_course_path(@user, course) %>">
      <td class="col-lg-4"><a><%= link_to course.title, user_course_path(@user, course) %></a></td>
      <td class="col-lg-4"><%= course.code %></td>
      <td class="col-lg-4" align="center">
            <%= link_to edit_user_course_path(@user, course) do %>
              <span class="glyphicon glyphicon-edit" ></span>
            <% end %>

            <%= link_to user_course_path(@user, course),
                method: :delete,
                data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash" ></span>
            <% end %>
      </td>

    </tr>
  <% end %>
  <script>
  $("tr[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>
</table>
</div>

app/views/courses/new.html.erb
<center>
    <br>
    <div>

        <h1>New Course</h1>

        <%= render partial: 'form', locals: {cancel_path: user_courses_path(@user, @course), cancel_text: "Cancel"} %>

    </div>
</center>

app/views/courses/quiz.html.erb
<script> 
  var flashcard_url = "<%= url_for(controller:'courses', action:'flashcard') %>"; 
  var note_upload_url = "<%= url_for(controller:'courses', action:'updateNotes') %>";
  drawFlashcard('quiz'); // draw initial card
</script>
<center>
    <div>
    <%= render 'header', course: "", edit: "", students: "", quiz: "active", assignments: "", polls: "" %>
    <center>
      <div class = "container">
        <div class="row">
          <div class = "col-lg-4"></div>
            <div class = "col-lg-4">
            <h1>Face/Name Quiz</h1>
              <div class = "flashcard">
                <%= image_tag "/images/defaults/flashcard/missing.png", :id => "student-picture", :style => "width:300px;height:300px;", :onclick => "drawFlashcard('quiz')" %>
                <div class= "flashcard-info" id="flashcard-container" onclick="show()">
                  <div class= "flashcard-info" id="flashcard-info">
                    <h2 id="student-name">Name</h2>
                    <span>Notes:</span>
                    <textarea rows=5 id="student-notes" onkeyup="updateNotes()"></textarea>
                  </div>
                </div>
              </div>
              <button type="button" class ="btn" onclick="toggleShow()">Show/Hide Info</button>
              <button type="button" class ="btn" onclick="drawFlashcard('quiz')">Draw Flashcard</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </br>
</center>

app/views/courses/show.html.erb
<%= csrf_meta_tag %>
<%= javascript_include_tag "dropzone.js" %>
<%= render 'header', course: "active", students: "", quiz: "", assignments: "", polls: "" %>
<center>
  <div>
    <div class = "container">
      <div class="row">
        <div class = "col-lg-4">
        </div>
        <div class = "col-lg-4">
          <h3>Flashcards</h3>
          <div class = "flashcard" id="flashcard-info" onclick="drawFlashcard('equity')">
            <%= image_tag "/images/defaults/flashcard/missing.png", :id => "student-picture", :style => "width:300px;height:300px;" %>
            <h4 id="student-name">Click to Draw</h4>
          </div>
          <div class ="btn" onclick="drawFlashcard('equity')">Draw Flashcard</div>  
        </div>
        <div class ="col-lg-4">
          <br>
          <br>
          <a class = "btn" <%= link_to "Edit Course", edit_user_course_path(@user, @course) %></a>
          <br>
          <button class="btn" onclick="toggleHide()">Order Students</button>
          <div id="toggleable"; style = "display:none">
            <h4>Order Students</h4>
            <%= form_tag user_course_path(@user, @course) do %>
              <%= text_area :flashcard_order, :edit_flashcard_order %>
              <%= submit_tag "Order Students" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>
<script>
  // so we can access the correct urls in the .js files
  var flashcard_url = "<%= url_for(controller:'courses', action:'flashcard') %>";
</script>

app/views/courses/student_index.html.erb
<%= render 'header', course: "", students: "active", quiz: "", assignments: "", polls: "" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-6"><h1>Student Roster</h1></div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6" >
      <h1 class="right-align"><%= link_to "Add Student", new_user_course_student_path(@user, @course), :class => 'btn'%></h1>
    </div>
  </div>
<center>
  <body>
    <table class="table table-hover table-responsive">
      <tr class="table-header">
        <th class="col-lg-3 col-md-3 col-sm-4">Name</th>
        <th class="col-lg-6 col-md-6 col-sm-4">Notes</th>
        <th class="col-lg-3 col-md-3 col-sm-4" > <center>Options</center></th>
      </tr>
      <% @course.students.each do |student| %>
        <tr data-link="<%= user_course_student_path(@user, @course, student) %>">
          <td class="col-lg-3 col-md-3 col-sm-4">
            <%= image_tag student.portrait.url(:small)%>
            <%= link_to student.name, user_course_student_path(@user, @course, student) %>
          </td>
          <td class="col-lg-6 col-md-6 col-sm-4"><%= student.notes %></td>
          <td class="col-lg-3 col-md-3 col-sm-4" align="center">
            <div class="row">
              <a class="col-4"><%= link_to edit_user_course_student_path(@user, @course, student) do %>
                <span class="glyphicon glyphicon-edit" ></span>
              <% end %></a>
              <a class="col-4"><%= link_to user_course_student_path(@user, @course, student),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } do %>
                     <span class="glyphicon glyphicon-trash" ></span>
                    <% end %></a>
              <br>
              <%= form_for [@user, @course, student], local: true, html: {:class => "form-horizontal"} do |form| %>
              <table>
                <td class="col-6">
                    <%= form.check_box :in_flashcards, :checked => student.in_flashcards %>
                    <%= form.label :in_flashcards, "Include in flashcards", :class => "control-label"  %>
                    <br>
                    <%= form.check_box :in_quiz, :checked => student.in_quiz %>
                    <%= form.label :in_quiz, "Include in quiz", :class => "control-label"  %>
                </td>
                <td class="col-6">
                  <%= form.submit "Confirm", :class => "btn"  %>
                <% end %>
                </td>
              </table>
            </div>
          </td>
        </tr>
      <% end %>
      <script> $("tr[data-link]").click(function() {
                window.location = $(this).data("link")
               })
      </script>
    </table>
  </body>
</center>
</div>
</br>
<center>
  <h4>Import Students</h4>
  <p>Upload a series of images in .png or .jpg format. The name of each image should be the name of the student with underscores instead of spaces (e.g., "john_smith.png" for "John Smith").
  <div class = "drop-area">
    <%= form_tag import_user_course_students_path(@user, @course),
      :class => "dropzone",
      multipart: true do %>
  </div>
    <%= submit_tag "Import" %>
    <% end %>
  <br>
  <br>
</center>